A='ATGTCTGAACACATCAGCCGATGGCTCTCTGTTACCCTCAATATAACGGGAACGGTGCACAGGGGGTCGGAACGCAGTTTCGTCAACTGTTAAGTCAGTTCATGAAAATATACTGTGGCTGGCCACGCAGTCTTCACCGTACCCCCAACCGGCAGCGACGGACGGTCATAAACGTTCTAGTCGCAATTGTATATATCCAGAGATCATTATCGGCTACAATCCTTGCGCTTTCGCGAATCGGTCTCTTGCTATGTAGAAGTTTTGTGATGATTCCCCTAGCCTGGCGGTGTACGGGACGGATATGGCCCGCGATGATGCTGCGAGGACATGAAGCACTAATACGGGGGCTAGTGATGCTTGTTCTACTGGCAGCCCTTCGTATGACTGTCCATTTGCAGCTTCCTTTGAAAGTCTTTTTTGACGATTGTATCGTTCTCTATAGTAAACTGGTGCTTCCCAGTCGTTTATGGTTCTATATCTGCGATCACCATTACGTATCAACAGTGCCGAAGACATACGAACGCCGTGCTGAATCTCGCCACTTTGTCGACTGAATGCAAGTATTGCTCTTTTGCTGAACGCTGCTCTGACATCCCCATCCGGCGCTCAAGCACGCCATGATTTTGACCTTCGCTTGTGCGGACTCATCGAAGGTTACCATAGCCGCATTGTTTCACTTTCGTTTGCCCTATGTAGCTTACGTAGTGTACATTCTCAGTGAAAATTTAGACTTTTATCCAGGCGGATTGATGGGGCTAGGTTACTCGGCCTGCGGGCCGGACGACCCCTTAGGAGCGATGTAATCACATTGCACCGTCGAGTTCATTACGCAGCTACGCAGGTGTTCGCCCCAAACGTATCCACGTTATTTCGTACTAGTCGTGTACATGCGGTCGTACATATCTATGACCTTAAGCAGTCATCTCCTCTGGCGGAAGACGCTTTAGAATGGTAAAGTAG'
a='CCATCCGGCGCTCAAGCACGCCATG'
b='TGCGCTTTCGCGAATCGGTCTC'
c='ATAACGGGAACGGTGCACA'
d='AGCGACGGAC'
e='GGATTGATGGGGCTAGGTTACTCGGCCTGCGGGCCGGACGACCCCTTAG'
f='ACCATAGCCGCATTGTTTCACTTTCGTTTGCCCTATGTA'
g='GCCCTTCGTATGACTGTCCATTTGCAGCTTCCTTTGAAAGTCTTTTTT'
h='ATGGCCCGCGATGATGCTGCGAGGACATGAAGCA'
i='GTGATGATTCCCCTAGC'
j='TCTGCGATCACCATTACGTATCAAC'
k='CATGCGGTCGTACATATCTATGACCTTAAGCAGTCATCTCC'
l='ATACTGTGGCT'
m='TGAATCTCGCCACTTTGTCGACTGAATGCAAGTATTGCTCTTTTGCTG'
n='CTCTATAGTAAACTGGTGCTTCCCA'
o='ATTGCACCGTCGAGTTCATTACGCAGCTACG'

LIST = [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o]
LIST.sort(key=len)
LIST.reverse()

for i in LIST:
    A=A.replace(i,"")

exon= A.replace('T', 'U')

def translate(a):
    RNA_seq = a
    codon_table ={'UUU': 'F', 'UUC': 'F', 'UUA': 'L', 'UUG': 'L', 'UCU': 'S', 'UCC': 'S', 'UCA': 'S', 'UCG': 'S', 'UAU': 'Y', 'UAC': 'Y', 'UAA': '*', 'UAG': '*', 'UGU': 'C', 'UGC': 'C', 'UGA': '*', 'UGG': 'W', 'CUU': 'L', 'CUC': 'L', 'CUA': 'L', 'CUG': 'L', 'CCU': 'P', 'CCC': 'P', 'CCA': 'P', 'CCG': 'P', 'CAU': 'H', 'CAC': 'H', 'CAA': 'Q', 'CAG': 'Q', 'CGU': 'R', 'CGC': 'R', 'CGA': 'R', 'CGG': 'R', 'AUU': 'I', 'AUC': 'I', 'AUA': 'I', 'AUG': 'M', 'ACU': 'T', 'ACC': 'T', 'ACA': 'T', 'ACG': 'T', 'AAU': 'N', 'AAC': 'N', 'AAA': 'K', 'AAG': 'K', 'AGU': 'S', 'AGC': 'S', 'AGA': 'R', 'AGG': 'R', 'GUU': 'V', 'GUC': 'V', 'GUA': 'V', 'GUG': 'V', 'GCU': 'A', 'GCC': 'A', 'GCA': 'A', 'GCG': 'A', 'GAU': 'D', 'GAC': 'D', 'GAA': 'E', 'GAG': 'E', 'GGU': 'G', 'GGC': 'G', 'GGA': 'G', 'GGG': 'G'}
    start_codon = RNA_seq.find('AUG')
    AA_seq = []
    i = start_codon
    while i < len(RNA_seq)-2:
        codon = RNA_seq[i:i+3]
        AA = codon_table[codon]
        if AA == '*':
            break
        else:
            i+=3
        AA_seq.append(AA)
    return ''.join(AA_seq)

translate(exon)