def find_motif(s,t):
    positions = ''
    for i in range(len(s)):
        if s[i] == t[0]:
            if s[i:i+len(t)] == t:
                positions += str(i+1)+' '
    return positions
a='AATACGTCACGTCACTAGAACCGTCACTGCTGCGTCACTCAGGCGTCACTGTCTTTGATCCAGCTCGTCACTTTGCGTCACTCGTCACTGCGTCACTATTCACTTACGTCACTGCTTCGTCACTCGTCACTACTGCGTCACTGGACGTCACTTCGTCACTTCGTCACTTCGTCACTCCTCGTCACTTCGTCACTCGTCACTTCAGTATACGTCACTGGCGTCACTCGTCACTCGTCACTCGTCACTCGTCACTCGTCACTACGTCACTGACCGTCACTCGCCGTCACTCGTCACTCACTCACGTCACTGCAAAGCTGGCTCCGTCACTCGTCACTGACGCGTCACTATCGTCACTGCGGGAATTGACGTCACTCCGTCACTAGTCTTCCCCGGAACGTCACTCCGTCACTAGAGCTTGGCCGCGTCACTGTGCATCCAGTCAAACCGTCACTCCGTCACTAACATGCGTCACTTTGGCTTCCGTCACTGACGCCGTCACTCGAGCAACCGTCACTATGGCGTCACTGCCGTCACTCGTCACTCGTCACTTCACCCGCGTCACTTGGGCAACGTCACTACCGTCACTTCGGGCGTCACTGCGAACGTCACTCGTCACTGCGTCACTCCCGTCACTTTCGTCACTTTGACGTCACTCGTCACTTCGTCACTGAGTTGGACCGTCACTTAGCGTCACTGACGTCACTCGTCACTCTACAACGTCACTGCATCGTCACTGCGTCACTCGTCACTCGTCACTCGTCACTTCGTCACTCCGTCACTACCGTCACTCGTCACTACCCCTCGTCACTCGTCACTCGTCACTCGTCACTGAAATCTCCGTCACTGCGTCACTG'
b='CGTCACTCG'

find_motif(a,b)
